### ISSUE TITLE
Concerning tasks

### ISSUE THREAD

**Issue by MichaelYusko** [guyskk/curequests#1]
Hey @guyskk really interesting idea to use `requests` package, `async/await` syntax, would be cool, if I can help you, let me know.

Cheers!

**Comment by guyskk** [comment]
Great! I just create a project in https://github.com/guyskk/curequests/projects/1.
To contribute to this project, just fork + pull request, and add what you are doing to **In progress** card before coding. Feel free to tell me if you have any questions.

#### About the source code:

I follow the structure of https://github.com/requests/requests, and depends on it. Some code are copyed from requests(Copy if necessary), it's better to read requests' implements before add features.

**Comment by MichaelYusko** [comment]
@guyskk Okay! nice.
Maybe would be cool, if you will create  an ticket for me, what I need to do.

First ticket for good start;)

**Comment by guyskk** [comment]
@MichaelYusko https://github.com/guyskk/curequests/projects/1#card-5395356

**Comment by MichaelYusko** [comment]
@guyskk Thanks, will start work on ticket tomorrow.

**Comment by guyskk** [comment]
Hi @MichaelYusko , I just implemented `chunk_size` params.
If you still interested in the project or have problems with it, please tell me. My email: guyskk@qq.com.
