### ISSUE TITLE
Versioned test suite

### ISSUE THREAD

**Issue by jayvdb** [guyskk/curequests#45]
The PyPI releases do not include tests, and there are no GitHub releases, so I can not get a stable URL for fetching tests of a release

**Comment by guyskk** [comment]
Thanks for your suggestion. I just release[ 0.4.1](https://github.com/guyskk/curequests/releases) for current master branch.

I suggest use aiohttp instead of this library because asyncio is main stream. 
And I'm not active support this library.

**Comment by jayvdb** [comment]
Thanks
